services:
  - type: web
    name: solar-panel-fault-detector
    env: docker
    healthCheckPath: /health
    region: oregon  # Can be changed based on requirements
    plan: standard  # Adjust based on resource needs
    numInstances: 1
    buildCommand: docker build -t solar-panel-detector .
    startCommand: docker run -p $PORT:$PORT -e PORT=$PORT solar-panel-detector
    envVars:
      - key: PORT
        value: 10000
      - key: MODEL_BATCH_SIZE
        value: 32
      - key: MODEL_NUM_WORKERS
        value: 4
      - key: MLFLOW_TRACKING_URI
        sync: false  # Indicates this should be set manually in Render dashboard
      - key: WANDB_API_KEY
        sync: false  # Indicates this should be set manually in Render dashboard
      - key: MODEL_URL
        value: https://huggingface.co/VishalGorule09/SolarPanelModel/resolve/main/variables.data-00000-of-00001
    autoDeploy: true
    disk:
      name: artifacts
      mountPath: /app/artifacts
      sizeGB: 10  # Adjust based on model size and storage needs