# API Configuration
API_URL = "http://localhost:5000"  # Change this for production deployment
RENDER_API_KEY=rnd_bn4oOO6D2yoPrfA9jXJiw2spFWF4

# Monitoring Configuration
ENABLE_AUTO_REFRESH = true
REFRESH_INTERVAL = 60  # seconds

# Security
MAX_BATCH_SIZE = 32
ALLOWED_MIME_TYPES = ["image/jpeg", "image/jpg", "image/png"]