
services:
  # Web service
  - type: web
    name: solar-panel-fault-detector
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 7860
    healthCheckPath: /
    